### PR TITLE
Fixes #784, #790, #802. Fixed several issues regarding timestamping o…

### LINKED ISSUE #784: Incorrect attribute 'time_increment' in History monthly collection files
I ran a 1-year GCHP simulation using MAPL 2.6.3 with the `monthly` collection option turned on in `HISTORY.rc`. The time variable has attribute `time_increment` which I would expect to be the duration of the month per file. Instead it is 7440000 for each month. This corresponds to the `duration` setting otherwise ignored when `monthly` is enabled.

For example, the time information for June is this:
```
        float time(time) ;
                time:begin_date = 20180601 ;
                time:begin_time = 0 ;
                time:long_name = "time" ;
                time:time_increment = 7440000 ;
                time:units = "minutes since 2018-06-01 00:00:00" ;
```
 This is a problem since no information other than `time_increment` is present to infer the file is a monthly average. The way it is now someone may think it is the average over 31 days starting on June 1 which is incorrect.

### LINKED ISSUE #802: Option 'timestampEnd' incorrectly prevents time-averaging in History
If a time-averaged collection specifies 'timestampEnd' then the variable "average" is not set properly, and as a result, no averaging is performed.

### PR DESCRIPTION
**Pull request by atrayano**
…ffsets and incorrect time_increment attribute for monthly averaged output. Added new option "timestampStart".

## Related Issue

Closes #802, #790 and #784

## Motivation and Context

This fixes several issues regarding time stamping of averaged files, as well as incorrect time increment metadata for a monthly averaged collections
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

File: base/MAPL_TimeMethods.F90 [hunk 1]
```diff
@@ -61,6 +62,16 @@ subroutine get(this,clock,rc)
      _RETURN(_SUCCESS)
   end subroutine get
        
+  subroutine setFrequency(this,frequency,rc)
+     class(TimeData) :: this
```
Comment (tclune) [inline base/MAPL_TimeMethods.F90:66]: missing `INTENT` attribute.

**Review by tclune — CHANGES_REQUESTED** [review]
One minor fix requested.

**Comment by atrayano** [comment]
Thanks for catching! Done. Added the missing INTENT

**Review by tclune — APPROVED** [review]
