### PR TITLE
Fixes #756. The bug was related to putting the split fields in the sa…

### LINKED ISSUE #756: Bug with splitField and identical fields in different collections
User @rmontuoro reported an issue when testing the UFS that if he tried to write two distinctly named collections with identical fields (one is time averaged, other is not) like so:
```
  inst_3d_aer.format:     'CFIO' ,
  inst_3d_aer.descr:      '3d,3-Hourly,Instantaneous,Model-Level,Analysis,Aerosol Concentrations',
  inst_3d_aer.template:   '%y4%m2%d2_%h2%n2z.nc4',
  inst_3d_aer.mode:       'instantaneous',
  inst_3d_aer.grid_label:  PC720x361-DC ,
  inst_3d_aer.splitField:  1,
  inst_3d_aer.frequency:   010000 ,
  inst_3d_aer.duration:    010000 ,
  inst_3d_aer.ref_time:    000000 ,
  inst_3d_aer.nbits:      10,
  inst_3d_aer.fields:   'DU'           , 'DU'   ,
                        'SS'           , 'SS'   ,
                      ::

  tavg_3d_aer.format:     'CFIO' ,
  tavg_3d_aer.template:   '%y4%m2%d2_%h2%n2z.nc4',
  tavg_3d_aer.mode:       'time-averaged',
  tavg_3d_aer.grid_label:  PC720x361-DC ,
  tavg_3d_aer.splitField:  1,
  tavg_3d_aer.frequency:   020000 ,
  tavg_3d_aer.duration:    020000 ,
  tavg_3d_aer.ref_time:    000000 ,
  tavg_3d_aer.nbits:      10,
  tavg_3d_aer.fields:   'DU'           , 'DU'   ,
                        'SS'           , 'SS'   ,
                      ::
```
This looks like an issue with the split option. I was able to reproduce this in a hack of my ExtDataDriver and see this:
```
pe=00000 FAIL at line=03051    MAPL_Base.F90                            <status=13>
pe=00000 FAIL at line=02867    MAPL_HistoryGridComp.F90                 <status=13>
pe=00000 FAIL at line=01445    MAPL_HistoryGridComp.F90                 <status=13>
pe=00000 FAIL at line=01839    MAPL_Generic.F90                         <needs informative message>
pe=00000 FAIL at line=00379    ExtDataDriverGridComp.F90                <status=1>
pe=00000 FAIL at line=00535    ExtDataDriverGridComp.F90                <status=1>
pe=00000 FAIL at line=00128    ExtDataDriverMod.F90                     <status=1>
pe=00000 FAIL at line=00024    ExtDataDriver.F90                        <status=1>
```
From what I can tell, it looks like the split option adds the split fields back to the export state of the component when first initializing history. It looks like if you have two collections with the split and the same fields it fails with a trying to add duplicate field error. So the logic here probably needs to check if we have already added the split field for the original in that component.

### PR DESCRIPTION
**Pull request by atrayano**
…me export state as the original field. When more than 1 collection is splitting the same field, this resulted in duplicate items in the export state

## Description
we now check if the split field is already in the export state. If "yes" we do not put it again

## Related Issue

#756, #673

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GEOSgcm (if non-trivial)
- [ x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x ] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

File: gridcomps/History/MAPL_HistoryGridComp.F90 [hunk 1]
```diff
@@ -5170,5 +5180,41 @@ subroutine RecordRestart( gc, import, export, clock, rc )
     _RETURN(ESMF_SUCCESS)
   end subroutine RecordRestart
 
+  subroutine  checkIfStateHasField(state, fieldName, hasField, rc)
```
Comment (tclune) [inline gridcomps/History/MAPL_HistoryGridComp.F90:5183]: No change requested,  but in the future consider that a LOGICAL function would have expressed the functionality more cleanly.

File: gridcomps/History/MAPL_HistoryGridComp.F90 [hunk 2]
```diff
@@ -5170,5 +5180,41 @@ subroutine RecordRestart( gc, import, export, clock, rc )
...
+       if(itemTypeList(I)/=ESMF_STATEITEM_FIELD) cycle
+       if(itemNameList(I)==fieldName) then
+          hasField = .true.
+          exit
+       end if
+    end do
+    deallocate(itemNameList, stat=status)
+    _VERIFY(STATUS)
+    deallocate(itemTypeList, stat=status)
+    _VERIFY(status)
```
Comment (tclune) [inline gridcomps/History/MAPL_HistoryGridComp.F90:5214]: Unnecessary.  Unsaved ALLOCATABLE's are automatically deallocated on exit.

Again - no change requested.   Just for the future.

**Review by tclune — APPROVED** [review]

**Comment by rmontuoro** [comment]
This PR fixes the issue occurring with UFS-GOCART.
