### PR TITLE
Fixes #4059

### LINKED ISSUE #4059: Regrid brackets only when attribute indicates
The plan for this had always been to put something in FieldBundleSet (and Get) to specify when a field node in a bracket has changed.   

The tricky part is how to *clear* this entry.    In theory this can be done inside of RegridTransform, but this will fail if the same export from ExtData is regridded to distinct geoms.     Instead, I think ExtData will need to clear the setting on entry.

### PR DESCRIPTION
**Pull request by bena-nasa**
Fixes #4059 

This allows extdata to set a flag that the regridding can queue off of to decide whether the bracket needs regridding.
As usual confirmed it work via prints but couldn't think of a good test.

I didn't know how far to take this. I added a new FieldBundle method to detect if the attribute is present, but only for the new one, I didn't do it for every option for fieldGet/Set

Also this is only for fieldBundles so no way if you are just regridding a field you could do something similar.

This was really the minimum needed...
Thought I would put it out here before going more crazy

## Types of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
- [ ] Refactor (no functional changes, no api changes)

## Checklist
- [ ] Tested this change with a run of GEOSgcm
- [ ] Ran the Unit Tests (`make tests`)

### CODE REVIEW

File: field_bundle/FieldBundleInfo.F90 [hunk 1]
```diff
@@ -209,4 +226,28 @@ end function to_string
              
    end subroutine fieldbundle_set_internal
 
+   subroutine fieldbundle_is_present_internal(info, unusable, namespace, do_regrid_transform, rc)
```
Comment (tclune) [inline field_bundle/FieldBundleInfo.F90:229]: I don't immediately see why this procedure is needed.

File: generic3g/transforms/RegridTransform.F90 [hunk 2]
```diff
@@ -142,13 +143,46 @@ subroutine update(this, importState, exportState, clock, rc)
...
+   function check_do_transform(fb_in, fb_out, rc) result(do_transform)
+      logical :: do_transform
+      type(ESMF_FieldBundle), intent(in) :: fb_in
+      type(ESMF_FieldBundle), intent(in) :: fb_out
+      integer, optional, intent(out) :: rc
+
+      logical :: do_trans_in, do_trans_out, present_in, present_out 
+      integer :: status
+
+      call MAPL_FieldBundleIsPresent(fb_in, do_regrid_transform=present_in, _RC)
```
Comment (tclune) [inline generic3g/transforms/RegridTransform.F90:165]: OK - I see "why" now, but ...   Can't we simply arrange it so that there is always a value?    Just add a call to FieldBundleSet() in BracketClassAspect::create().

File: generic3g/transforms/RegridTransform.F90 [hunk 3]
```diff
@@ -142,13 +143,46 @@ subroutine update(this, importState, exportState, clock, rc)
...
+      if (present_in) then
+         call MAPL_FieldBundleGet(fb_in, do_regrid_transform=do_trans_in, _RC)
+      end if
+      call MAPL_FieldBundleIsPresent(fb_out, do_regrid_transform=present_out, _RC)
```
Comment (tclune) [inline generic3g/transforms/RegridTransform.F90:169]: No - the output field should not be responsible for controlling do_regrid transform.   We probably need to discuss.

File: field_bundle/FieldBundleGet.F90 [hunk 4]
```diff
@@ -53,6 +54,7 @@ subroutine bundle_get(fieldBundle, unusable, &
       character(:), optional, allocatable, intent(out) :: standard_name
       character(:), optional, allocatable, intent(out) :: long_name
       type(StateItemAllocation), optional, intent(out) :: allocation_status
+      logical, optional, intent(out) :: do_regrid_transform
```
Comment (tclune) [inline field_bundle/FieldBundleGet.F90:57]: I'm thinking that we can probably find a better name here, as it does not quite reflect the intent.

We are not so much telling upstream to regrid (e.g., if the geoms are the same, it should not trigger a regrid), as saying that the bundle data has been updated.

Something like `bracket_data_changed`.  (Not wed to the details here.)

**Review by tclune — APPROVED** [review]
