### PR TITLE
Fixes #3436 - Changes to get the tests for GetHorzIJIndex to pass on NAG

### LINKED ISSUE #3436: MAPL2 OpenMP Test fails with NAG on Linux
With the introduction of the OpenMP tests from @aoloso in #3401, my NAG MAPL builds on discover are failing with:

```
The following tests FAILED:
	 75 - GetHorzIJIndex_NO_OMP (Failed)
	 76 - GetHorzIJIndex_OMP_1_thread (Failed)
	 77 - GetHorzIJIndex_OMP_4_thread (Failed)
Errors while running CTest
```

The NoOMP seems to die with:
```
    Start 75: GetHorzIJIndex_NO_OMP
1/3 Test #75: GetHorzIJIndex_NO_OMP ............***Failed    1.23 sec
      MAPL: No configure file specified for logging layer.  Using defaults.
 Starting pFIO input server on Clients
 Starting pFIO output server on Clients
      MAPL: Running with MOAB library for ESMF Mesh: F
     SHMEM: NumCores per Node = 6
     SHMEM: NumNodes in use   = 1
     SHMEM: Total PEs         = 6
     SHMEM: NumNodes in use  = 1
 Integer*4 Resource Parameter: BEG_DATE:20070801 0
 Integer*4 Resource Parameter: END_DATE:29990302 210000
pe=00005 FAIL at line=00318    MAPL_CapGridComp.F90                     <status=51>
pe=00005 FAIL at line=00856    MAPL_CapGridComp.F90                     <status=51>
pe=00005 FAIL at line=00349    MAPL_Cap.F90                             <status=51>
pe=00005 FAIL at line=00258    MAPL_Cap.F90                             <status=51>
pe=00005 FAIL at line=00192    MAPL_Cap.F90                             <status=51>
pe=00005 FAIL at line=00169    MAPL_Cap.F90                             <status=51>
pe=00005 FAIL at line=00018    driver.F90                               <status=51>
```
and the other seem to fail on the same line.

I'm testing now on Bucy to see if it happens there.

### PR DESCRIPTION
**Pull request by aoloso**
## Types of change(s)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
- [ ] Refactor (no functional changes, no api changes)

## Checklist
- [ X] Tested this change with a run of GEOSgcm
- [ X] Ran the Unit Tests (`make tests`)

## Description
Tests for GetHorzIJIndex were failing with the NAG compiler in debug mode due to strict enforcements of the fortran standard. 
## Related Issue
None

### CODE REVIEW

File: gridcomps/Cap/MAPL_CapGridComp.F90 [hunk 1]
```diff
@@ -1024,7 +1031,7 @@ subroutine run_MAPL_GridComp(gc, phase, rc)
     type (MAPL_MetaComp), pointer :: MAPLOBJ
     procedure(), pointer :: root_set_services
 
-    cap => get_CapGridComp_from_gc(gc)
+    cap => get_CapGridComp_from_gc(gc, _RC)
```
Comment (tclune) [inline gridcomps/Cap/MAPL_CapGridComp.F90:1034]: I thought there were more calls that needed the new optional argument?

**Review by tclune — CHANGES_REQUESTED** [review]
Needs an entry in the ChangeLog and I think some RC things were dropped in this PR.

**Review by tclune — APPROVED** [review]
